before_script:
  - "export PATH=$PATH:/usr/local/bin"
  - "export PROJECT_DIR=/var/www/fennec_ui"
  - "export BUILD_DIR=~/fennec_ui"

  # Information
  - "whoami"
  - "echo \"Current location:\" `pwd`"
  - "nvm --version"
  - "nvm install 6 &> /dev/null"
  - "nvm use 6"
  - "node --version"
  - "npm install -g yarn > /dev/null"
  - "yarn --version"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - "export SOURCE_DIR=`pwd`"
    - "export API_HOST=app.gapbor.uz"
    - "yarn install"
    - "yarn build"
    - "rm -rf ~/fennec_ui_${CI_BUILD_REF_NAME}"
    - "mkdir ~/fennec_ui_${CI_BUILD_REF_NAME}"
    - "cp -R ${SOURCE_DIR}/dist/* ~/fennec_ui_${CI_BUILD_REF_NAME}"
  tags:
    - staging

test:
  stage: test
  script:
    - "export SOURCE_DIR=`pwd`"
    - "yarn install"
    - "yarn lint"
#    - "export DISPLAY=':99.0'"
#    - "Xvfb :99 -screen 0 1024x768x24 +extension RANDR > /dev/null 2>&1 &"
#    - "yarn test:server"
#    - "kill %1"
  tags:
    - staging

deploy:
  stage: deploy
  script:
    - "rm -rf ${PROJECT_DIR}/*"
    - "cp -R ~/fennec_ui_${CI_BUILD_REF_NAME}/* ${PROJECT_DIR}/"
  only:
    - master
  tags:
    - staging
