/**
 * Action Types
 */
export const SIGN_IN = 'SIGN_IN'

export const DAILY_ENTRY_LIST = 'DAILY_ENTRY_LIST'
export const DAILY_REPORT_LIST = 'DAILY_REPORT_LIST'
export const DAILY_REPORT_LIST_CSV = 'DAILY_REPORT_LIST_CSV'
export const DAILY_ENTRY_ITEM = 'DAILY_ENTRY_ITEM'
export const DAILY_ENTRY_CREATE = 'DAILY_ENTRY_CREATE'

export const BALANCE_LIST = 'BALANCE_LIST'
export const BALANCE_LIST_CSV = 'BALANCE_LIST_CSV'
export const BALANCE_ITEM = 'BALANCE_ITEM'
export const BALANCE_CREATE = 'BALANCE_CREATE'

export const SHOP_LIST = 'SHOP_LIST'
export const SHOP_LIST_CSV = 'SHOP_LIST_CSV'
export const SHOP_ITEM = 'SHOP_ITEM'
export const SHOP_CREATE = 'SHOP_CREATE'

export const CLIENT_CREATE = 'CLIENT_CREATE'
export const CLIENT_LIST = 'CLIENT_LIST'

export const DASHBOARD_CHART_PIE = 'DASHBOARD_CHART_PIE'
export const DASHBOARD_CHART_LINE = 'DASHBOARD_CHART_LINE'

export const BROKER_LIST = 'BROKER_LIST'
export const BROKER_ITEM = 'BROKER_ITEM'
export const BROKER_CREATE = 'BROKER_CREATE'
export const BROKER_EDIT = 'BROKER_EDIT'
export const BROKER_DELETE = 'BROKER_DELETE'

export const MONTHLY_REPORT_LIST = 'MONTHLY_REPORT_LIST'
export const MONTHLY_REPORT_ITEM = 'MONTHLY_REPORT_ITEM'
export const MONTHLY_REPORT_CREATE = 'MONTHLY_REPORT_CREATE'
export const MONTHLY_REPORT_EDIT = 'MONTHLY_REPORT_EDIT'
export const MONTHLY_REPORT_DELETE = 'MONTHLY_REPORT_DELETE'
export const MONTHLY_REPORT_LIST_CSV = 'MONTHLY_REPORT_LIST_CSV'

export const FUND_MANAGER_LIST = 'FUND_MANAGER_LIST'
export const FUND_MANAGER_ITEM = 'FUND_MANAGER_ITEM'
export const FUND_MANAGER_CREATE = 'FUND_MANAGER_CREATE'
export const FUND_MANAGER_EDIT = 'FUND_MANAGER_EDIT'
export const FUND_MANAGER_DELETE = 'FUND_MANAGER_DELETE'

