/**
 * Action Types
 */
export const SIGN_IN = 'SIGN_IN'

export const SHOP_LIST = 'SHOP_LIST'
export const SHOP_LIST_CSV = 'SHOP_LIST_CSV'
export const SHOP_ITEM = 'SHOP_ITEM'
export const SHOP_UPDATE = 'SHOP_UPDATE'
export const SHOP_CREATE = 'SHOP_CREATE'
export const SHOP_DELETE = 'SHOP_DELETE'

export const CASHBOX_LIST = 'CASHBOX_LIST'
export const CASHBOX_LIST_CSV = 'CASHBOX_LIST_CSV'
export const CASHBOX_ITEM = 'CASHBOX_ITEM'
export const CASHBOX_UPDATE = 'CASHBOX_UPDATE'
export const CASHBOX_CREATE = 'CASHBOX_CREATE'
export const CASHBOX_DELETE = 'CASHBOX_DELETE'

export const SUPPLY_LIST = 'SUPPLY_LIST'
export const SUPPLY_LIST_CSV = 'SUPPLY_LIST_CSV'
export const SUPPLY_ITEM = 'SUPPLY_ITEM'
export const SUPPLY_UPDATE = 'SUPPLY_UPDATE'
export const SUPPLY_CREATE = 'SUPPLY_CREATE'
export const SUPPLY_DELETE = 'SUPPLY_DELETE'

export const PRODUCT_LIST = 'PRODUCT_LIST'
export const PRODUCT_UPDATE = 'SHOP_UPDATE'
export const PRODUCT_CREATE = 'SHOP_CREATE'
export const PRODUCT_DELETE = 'SHOP_DELETE'

export const CATEGORY_LIST = 'CATEGORY_LIST'
export const CATEGORY_ITEM = 'CATEGORY_ITEM'
export const CATEGORY_UPDATE = 'CATEGORY_UPDATE'
export const CATEGORY_CREATE = 'CATEGORY_CREATE'
export const CATEGORY_DELETE = 'CATEGORY_DELETE'

export const SNACKBAR = 'SNACKBAR'
export const SNACKBAR_OPEN = `${SNACKBAR}_OPEN`
export const SNACKBAR_CLOSE = `${SNACKBAR}_CLOSE`
