import ApplicantGridList from './ApplicantGridList'
import {APPLICANT_CREATE_DIALOG_OPEN} from './ApplicantCreateDialog'
import {APPLICANT_FILTER_KEY, APPLICANT_FILTER_OPEN} from './ApplicantFilterForm'

const APPLICANT_DELETE_DIALOG_OPEN = 'openDeleteDialog'
const APPLICANT_UPDATE_DIALOG_OPEN = 'openUpdateDialog'
const APPLICANT_MAIL_DIALOG_OPEN = 'openMailDialog'
export {
  APPLICANT_CREATE_DIALOG_OPEN,
  APPLICANT_UPDATE_DIALOG_OPEN,
  APPLICANT_DELETE_DIALOG_OPEN,
  APPLICANT_FILTER_KEY,
  APPLICANT_FILTER_OPEN,
  APPLICANT_MAIL_DIALOG_OPEN,
  ApplicantGridList
}
