import {getLanguage} from '../helpers/storage'

const uz = {
    'Клиенты': 'Mijozlar',
    'Наименование': 'Nomi',
    'По рекомендации': 'Tavsiya qilgan',
    'Адрес': 'Manzil',
    'Дата добавления': 'Yaratilgan sanasi',
    'Сотрудник': 'Ishchi',
    'Логин': 'Login',
    'Права доступа': 'Foydalanish huquqi',
    'Телефон': 'Telefon',
    'Должность': 'Mavqeyi',
    'Статус': 'Holati',
    "Неизвестно": "Aniqlanmadi",
    "Добавить клиента": "Mijoz qo'shish",
    "Изменение клиента": "Mijozni o'zgartirish",
    "Организация": "Tashkilot",
    "Добавить в черный список": "Qora ro'yxatga qo'shish",
    "Сохранить": "Saqlash",
    "Местположение": "Manzil",
    "Контактные данные": "Aloqa ma'lumotlarini",
    "Контактное лицо": "Aloqadagi shaxs",
    "Email": "Email",
    "Телефон номер": "Telefon raqami",
    "Подтверждение удаления": "O'chirishni tasdiqlash",
    "Удалить": "O'chrish",
    "Вы уверены что хотите удалить эти данные?": "Haqiqatan ham bu ma'lumotlarni o'chirib tashlamoqchimisiz?",
    "Подтверждение отмены": "Bekor qilishni tasdiqlash",
    "Подтвердить": "Tasdiqlash",
    "Вы уверены что хотите отменить эти данные?": "Haqiqatan ham bu ma'lumotlarni bekor qilmoqchimisiz?",
    "Выполнить": "Bajarish",
    "Да": "Ha",
    "Подтверждение запроса": "So'rovni tasdiqlash",
    "Клиент в черном списке": "Qora ro'yxatdagi mijoz",
    "Изменить": "Tahrirlash",
    "Заказ": "Buyurtma",
    "Магазин": "Do'kon",
    "Инициатор": "Initsiator",
    "Сумма заказа": "Buyurtmaning miqdori",
    "Дата доставки": "Etkazib berish sanasi",
    "Дата создания": "Yaratilgan sana",
    "Оплата ожидается": "To'lov kutmoqda",
    "Ожидаемый платеж": "Kutilayotgan to'lov",
    "Долг": "Qarz",
    "Оплата ожидалась": "To'lov ushlanib qoldi",
    "Оплата ожидается сегодня": "To'lov bugun kutilmoqda",
    "Сумма": "Miqdori",
    "В процессе": "Jarayonda",
    "Есть на складе": "Omborda bor",
    "Доставлен": "Yetkazib berildi",
    "Передан доставщику": "Eltuvchiga berildi",
    "Заказ отменен": "Buyurtma bekor qilindi",
    "Не подтвержден": "Tasdiqlanmagan",
    "Оплачено": "To'langan",
    "Обновить список": "Ro'yxatni yangilash",
    "Отфильтровать неподтвержденным заказам": "Tasdiqlanmagan buyurtmalarni filtrlash",
    "Отфильтровать по запрошенным заказам": "So'ralgan buyurtmalar bo'yicha filtrlash",
    "Отфильтровать по доступным заказам": "Mavjud buyurtmalar bo'yicha filtrlash",
    "Распечатать накладные": "Xarajatlarni chop etish",
    "Продажа товаров": "Tovarlarni sotish",
    "Скачать накладные": "Xarajatlarni yuklab olish",
    "Изменить выбранные заказы": "Tanlangan buyurtmalarni tahrirlash",
    "Сформировать Релиз": "Reliz yaratish",
    "Добавить заказ": "Buyurtma qo'shish",
    "Изменение заказа": "Buyurtmani o'zgartirish",
    "Добавление заказа": "Buyurtma qo'shish",
    "добавить": "qo'shish",
    "Клиент": "Mijoz",
    "Название магазина": "Do'kon nomi",
    "Недостаточно товаров на складе": "Omborda mahsulot yetarli emas",
    "Оплата": "To'lov",
    "Валюта": "Valyuta",
    "Прайс лист": "Narxlar ro'yxati",
    "Дата оплаты": "To'lov kuni",
    "Номер договора": "Shartnoma raqami",
    "Тип доставки": "Eltish turi",
    "Доставщик": "Eltuvchi",
    "Подтвержденный": "Tasdiqlangan",
    "Общая сумма заказа": "Buyurtmaning umumiy miqdori",
    "Далее": "Keyingisi",
    "Изменить заказ": "Buyurtmani o'zgartirish",
    "Оформить заказ": "Buyurtma berish",
    "Наличными": "Naqt",
    "Перечислением": "O'tkazma",
    "Стандартная": "Satandart",
    "Консигнация": "Konsignatsiya",
    "Индивидуальный": "Alohida",
    "Цены товаров будут изменены на": "Tovarlarning narxi o'zgaradi",
    "наличные": "naqt",
    "банковский счет": "bank hisob raqami",
    "Нет": "Yo'q",
    "добавить товар": "mahsulot qo'shish",
    "добавить из списка": "ro'yxatidan qo'shing",
    "Выберите прайс лист": "Narxlar ro'yxatini tanlang",
    "Тип товара": "Mahsulot turi",
    "Кол-во": "Soni",
    "Сумма за ед": "Birlik miqdori",
    "На складе": "Omboeda",
    "Цена": "Narx",
    "Всего": "Jami",
    "Вы еще не выбрали ни одного товара": "Siz birort ham mahsulot tanlamadizngiz",
    "Для добавления товаров": "Mahsulot qo'shish uchun",
    "выберите тип оплаты, валюту и прайс лист": "To'lov turi, valyutasi, narxlar ro'yxatini tanlang"
}
const en = {
    'Клиенты': 'Clients',
    'Наименование': 'Name',
    'Адрес': 'Address',
    'Дата добавления': 'Created date',
    'Сотрудник': 'Employee',
    'Логин': 'Login',
    'Права доступа': 'Access rights',
    'Телефон': 'Phone',
    'Должность': 'Position',
    'Статус': 'Status',
    "Неизвестно": "Unknown",
    "Добавить клиента": "Add client",
    "Изменение клиента": "Change client",
    "Организация": "Organization",
    "По рекомендации": "By recommendation",
    "Добавить в черный список": "Add to blacklist",
    "Сохранить": "Save",
    "Местположение": "Location",
    "Контактные данные": "Contact details",
    "Контактное лицо": "The contact person",
    "Email": "Email",
    "Телефон номер": "Phone number",
    "Подтверждение удаления": "Confirmation of deletion",
    "Удалить": "Delete",
    "Вы уверены что хотите удалить эти данные?": "Are you sure you want to delete this data ?",
    "Подтверждение отмены": "Confirmation of cancellation",
    "Подтвердить": "Confirm",
    "Вы уверены что хотите отменить эти данные?": "Are you sure you want to cancel this data ?",
    "Выполнить": "Done",
    "Да": "Yes",
    "Подтверждение запроса": "Confirm the request",
    "Клиент в черном списке": "Client in the black list",
    "Изменить": "Edit",
    "Заказ": "Order",
    "Магазин": "Market",
    "Инициатор": "Initiator",
    "Сумма заказа": "Order price",
    "Дата доставки": "Delivery date",
    "Дата создания": "Date of creation",
    "Оплата ожидается": "Payment is expected",
    "Ожидаемый платеж": "Expected payment",
    "Долг": "Debt",
    "Оплата ожидалась": "Payment was expected",
    "Оплата ожидается сегодня": "Payment is expected today",
    "Сумма": "The amount",
    "В процессе": "During",
    "Есть на складе": "In stock",
    "Доставлен": "Delivered",
    "Передан доставщику": "Transferred to the supplier",
    "Заказ отменен": "Order cancelled",
    "Не подтвержден": "Not confirmed",
    "Оплачено": "Paid",
    "Обновить список": "Update list",
    "Отфильтровать неподтвержденным заказам": "Filter out unconfirmed orders",
    "Отфильтровать по запрошенным заказам": "Filter by the requested orders",
    "Отфильтровать по доступным заказам": "Filter by available orders",
    "Распечатать накладные": "Print waybills",
    "Продажа товаров": "Sale of goods",
    "Скачать накладные": "Download invoices",
    "Изменить выбранные заказы": "Edit selected orders",
    "Сформировать Релиз": "Generate Release",
    "Добавить заказ": "Add an order",
    "Изменение заказа": "Changing an order",
    "Добавление заказа": "Adding an Order",
    "добавить": "add",
    "Клиент": "Client",
    "Название магазина": "Name of shop",
    "Недостаточно товаров на складе": "Not enough goods are in stock",
    "Оплата": "Payment",
    "Валюта": "Currency",
    "Прайс лист": "Price list",
    "Дата оплаты": "Date of payment",
    "Номер договора": "Contract number",
    "Тип доставки": "Type of delivery",
    "Доставщик": "Deliveryman",
    "Подтвержденный": "Confirmed",
    "Общая сумма заказа": "The total amount of the order",
    "Далее": "Further",
    "Изменить заказ": "Edit Order",
    "Оформить заказ": "Order Form",
    "Наличными": "In cash",
    "Перечислением": "Enumeration",
    "Стандартная": "Satandart",
    "Консигнация": "Consignment",
    "Индивидуальный": "Individual",
    "Цены товаров будут изменены на": "The prices of goods will be changed to",
    "наличные": "cash",
    "банковский счет": "bank account",
    "Нет": "No",
    "добавить товар": "add product",
    "добавить из списка": "add from list",
    "Выберите прайс лист": "Select the price list",
    "Тип товара": "Product type",
    "Кол-во": "Quantities",
    "Сумма за ед": "Amount for units",
    "На складе": "In Stock",
    "Цена": "Price",
    "Всего": "Total",
    "Вы еще не выбрали ни одного товара": "You have not selected any items yet",
    "Для добавления товаров": "To add products",
    "выберите тип оплаты, валюту и прайс лист": "Choose the type of payment, currency and price list"


}

const translate = (string) => {
    if (getLanguage() === 'uz') {
        return uz[string] || string
    } else if (getLanguage() === 'en') {
        return en[string] || string
    }
    return string
}

export default translate
