import ClientTransactionGridList from './ClientTransactionGridList'
import {CLIENT_TRANSACTION_FILTER_KEY, CLIENT_TRANSACTION_FILTER_OPEN} from './ClientTransactionFilterForm'

const CLIENT_TRANSACTION_CREATE_EXPENSE_DIALOG_OPEN = 'openCreateExpenseDialog'
const CLIENT_TRANSACTION_CREATE_INCOME_DIALOG_OPEN = 'openCreateIncomeDialog'
const CLIENT_TRANSACTION_UPDATE_EXPENSE_DIALOG_OPEN = 'openUpdateExpenseDialog'
const CLIENT_TRANSACTION_UPDATE_INCOME_DIALOG_OPEN = 'openUpdateIncomeDialog'
const CLIENT_TRANSACTION_CREATE_SEND_DIALOG_OPEN = 'openSendDialog'
const CLIENT_TRANSACTION_DELETE_DIALOG_OPEN = 'openDeleteDialog'

export {

    CLIENT_TRANSACTION_CREATE_EXPENSE_DIALOG_OPEN,
    CLIENT_TRANSACTION_CREATE_INCOME_DIALOG_OPEN,
    CLIENT_TRANSACTION_UPDATE_EXPENSE_DIALOG_OPEN,
    CLIENT_TRANSACTION_UPDATE_INCOME_DIALOG_OPEN,
    CLIENT_TRANSACTION_CREATE_SEND_DIALOG_OPEN,
    CLIENT_TRANSACTION_DELETE_DIALOG_OPEN,
    CLIENT_TRANSACTION_FILTER_KEY,
    CLIENT_TRANSACTION_FILTER_OPEN,
    ClientTransactionGridList
}
