import TransactionGridList from './TransactionGridList'
import {TRANSACTION_FILTER_KEY, TRANSACTION_FILTER_OPEN} from './TransactionFilterForm'

const TRANSACTION_CREATE_EXPENSE_DIALOG_OPEN = 'openCreateExpenseDialog'
const TRANSACTION_CREATE_INCOME_DIALOG_OPEN = 'openCreateIncomeDialog'
const TRANSACTION_UPDATE_EXPENSE_DIALOG_OPEN = 'openUpdateExpenseDialog'
const TRANSACTION_UPDATE_INCOME_DIALOG_OPEN = 'openUpdateIncomeDialog'
const TRANSACTION_CREATE_SEND_DIALOG_OPEN = 'openSendDialog'
const TRANSACTION_DELETE_DIALOG_OPEN = 'openDeleteDialog'
const TRANSACTION_CASH_DIALOG_OPEN = 'openAcceptCashDialog'
const TRANSACTION_ACCEPT_DIALOG_OPEN = 'openAcceptTransactionDialog'
const TRANSACTION_ACCEPT_CASH_DETAIL_OPEN = 'openAcceptCashDetail'
const TRANSACTION_INFO_OPEN = 'openTransactionInfo'

export {

    TRANSACTION_CREATE_EXPENSE_DIALOG_OPEN,
    TRANSACTION_CREATE_INCOME_DIALOG_OPEN,
    TRANSACTION_UPDATE_EXPENSE_DIALOG_OPEN,
    TRANSACTION_UPDATE_INCOME_DIALOG_OPEN,
    TRANSACTION_CREATE_SEND_DIALOG_OPEN,
    TRANSACTION_DELETE_DIALOG_OPEN,
    TRANSACTION_FILTER_KEY,
    TRANSACTION_FILTER_OPEN,
    TRANSACTION_CASH_DIALOG_OPEN,
    TRANSACTION_ACCEPT_DIALOG_OPEN,
    TransactionGridList,
    TRANSACTION_ACCEPT_CASH_DETAIL_OPEN,
    TRANSACTION_INFO_OPEN
}
